site_name: GeosysPy documentation
theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings

nav:
    - Home: index.md
    - Geosys class: geosys-reference.md
    - Constants: constants-reference.md
    - Utils: utils.md
    - Services: service-reference.md
