name: Publish package and docs test

on:
  push:
    tags:        
      - test-v**

jobs:
  deploy:

    runs-on: ubuntu-22.04


    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        pip install gdal==3.6.2
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install mkdocstrings-python
    - name: Build package
      run: make build
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    - run: mkdocs gh-deploy --force